In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

RAW_DIR = Path("../../data/raw/diabetes+130-us+hospitals+for+years+1999-2008")
REPORT_DIR = Path("../../reports/tables")
PROCESSED_DIR = Path("../../data/processed")

df = pd.read_csv(RAW_DIR / "diabetic_data.csv")

print(df.shape)
df.head()

(101766, 50)

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),?,6,25,1,1,...,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),?,1,1,7,3,...,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),?,1,1,7,2,...,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),?,1,1,7,2,...,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),?,1,1,7,1,...,No,Steady,No,No,No,No,No,Ch,Yes,NO

In [2]:
mapping_path = RAW_DIR / "IDs_mapping.csv"

with open(mapping_path, "r", encoding="utf-8") as f:
    mapping_text = f.read()

print(mapping_text[:10000])

admission_type_id,description
1,Emergency
2,Urgent
3,Elective
4,Newborn
5,Not Available
6,NULL
7,Trauma Center
8,Not Mapped
,
discharge_disposition_id,description
1,Discharged to home
2,Discharged/transferred to another short term hospital
3,Discharged/transferred to SNF
4,Discharged/transferred to ICF
5,Discharged/transferred to another type of inpatient care institution
6,Discharged/transferred to home with home health service
7,Left AMA
8,Discharged/transferred to home under care of Home IV provider
9,Admitted as an inpatient to this hospital
10,Neonate discharged to another hospital for neonatal aftercare
11,Expired
12,Still patient or expected to return for outpatient services
13,Hospice / home
14,Hospice / medical facility
15,Discharged/transferred within this institution to Medicare approved swing bed
16,Discharged/transferred/referred another institution for outpatient services
17,Discharged/transferred/referred to this institution for outpatient services
18,NULL
19,"Expired at home. Medicaid only, hospice."
20,"Expired in a medical facility. Medicaid only, hospice."
21,"Expired, place unknown. Medicaid only, hospice."
22,Discharged/transferred to another rehab fac including rehab units of a hospital .
23,Discharged/transferred to a long term care hospital.
24,Discharged/transferred to a nursing facility certified under Medicaid but not certified under Medicare.
25,Not Mapped
26,Unknown/Invalid
30,Discharged/transferred to another Type of Health Care Institution not Defined Elsewhere
27,Discharged/transferred to a federal health care facility.
28,Discharged/transferred/referred to a psychiatric hospital of psychiatric distinct part unit of a hospital
29,Discharged/transferred to a Critical Access Hospital (CAH).
,
admission_source_id,description
1, Physician Referral
2,Clinic Referral
3,HMO Referral
4,Transfer from a hospital
5, Transfer from a Skilled Nursing Facility (SNF)
6, Transfer from another health care facility
7, Emergency Room
8, Court/Law Enforcement
9, Not Available
10, Transfer from critial access hospital
11,Normal Delivery
12, Premature Delivery
13, Sick Baby
14, Extramural Birth
15,Not Available
17,NULL
18, Transfer From Another Home Health Agency
19,Readmission to Same Home Health Agency
20, Not Mapped
21,Unknown/Invalid
22, Transfer from hospital inpt/same fac reslt in a sep claim
23, Born inside this hospital
24, Born outside this hospital
25, Transfer from Ambulatory Surgery Center
26,Transfer from Hospice

In [3]:
work = df.copy()

work = work.replace("?", np.nan)

In [4]:
print("Original dataframe:")
print(df.isna().sum().sum())

print("After converting ?:")
print(work.isna().sum().sum())

Original dataframe:
181168
After converting ?:
374017

In [5]:
missing = pd.DataFrame({
    "missing_n": work.isna().sum(),
    "missing_pct": work.isna().mean() * 100
}).sort_values("missing_pct", ascending=False)

display(missing.head(20))

                   missing_n  missing_pct
weight                 98569    96.858479
max_glu_serum          96420    94.746772
A1Cresult              84748    83.277322
medical_specialty      49949    49.082208
payer_code             40256    39.557416
race                    2273     2.233555
diag_3                  1423     1.398306
diag_2                   358     0.351787
diag_1                    21     0.020636
encounter_id               0     0.000000
troglitazone               0     0.000000
tolbutamide                0     0.000000
pioglitazone               0     0.000000
rosiglitazone              0     0.000000
acarbose                   0     0.000000
miglitol                   0     0.000000
citoglipton                0     0.000000
tolazamide                 0     0.000000
examide                    0     0.000000
glipizide                  0     0.000000

In [6]:
missing.to_csv(
    REPORT_DIR / "uci_missingness_summary.csv"
)

In [7]:
rows = []

for col in work.columns:
    rows.append({
        "variable": col,
        "pandas_dtype": str(work[col].dtype),
        "unique_values": work[col].nunique(dropna=True),
        "missing_n": work[col].isna().sum(),
        "missing_pct": round(work[col].isna().mean() * 100, 2),
        "example_values": ", ".join(
            map(str, work[col].dropna().unique()[:5])
        )
    })

dictionary = pd.DataFrame(rows)

dictionary

,variable,pandas_dtype,unique_values,missing_n,missing_pct,example_values
0,encounter_id,int64,101766,0,0.00,"2278392, 149190, 64410, 500364, 16680"
1,patient_nbr,int64,71518,0,0.00,"8222157, 55629189, 86047875, 82442376, 42519267"
2,race,object,5,2273,2.23,"Caucasian, AfricanAmerican, Other, Asian, Hisp..."
3,gender,object,3,0,0.00,"Female, Male, Unknown/Invalid"
4,age,object,10,0,0.00,"[0-10), [10-20), [20-30), [30-40), [40-50)"
5,weight,object,9,98569,96.86,"[75-100), [50-75), [0-25), [100-125), [25-50)"
6,admission_type_id,int64,8,0,0.00,"6, 1, 2, 3, 4"
7,discharge_disposition_id,int64,26,0,0.00,"25, 1, 3, 6, 2"
8,admission_source_id,int64,17,0,0.00,"1, 7, 2, 4, 5"
9,time_in_hospital,int64,14,0,0.00,"1, 3, 2, 4, 5"
10,payer_code,object,17,40256,39.56,"MC, MD, HM, UN, BC"
11,medical_specialty,object,72,49949,49.08,"Pediatrics-Endocrinology, InternalMedicine, Fa..."
12,num_lab_procedures,int64,118,0,0.00,"41, 59, 11, 44, 51"
13,num_procedures,int64,7,0,0.00,"0, 5, 1, 6, 2"
14,num_medications,int64,75,0,0.00,"1, 18, 13, 16, 8"
15,number_outpatient,int64,39,0,0.00,"0, 2, 1, 5, 7"
16,number_emergency,int64,33,0,0.00,"0, 1, 2, 4, 3"
17,number_inpatient,int64,21,0,0.00,"0, 1, 2, 3, 6"
18,diag_1,object,716,21,0.02,"250.83, 276, 648, 8, 197"
19,diag_2,object,748,358,0.35,"250.01, 250, 250.43, 157, 411"
20,diag_3,object,789,1423,1.40,"255, V27, 403, 250, V45"
21,number_diagnoses,int64,16,0,0.00,"1, 9, 6, 7, 5"
22,max_glu_serum,object,3,96420,94.75,">300, Norm, >200"
23,A1Cresult,object,3,84748,83.28,">7, >8, Norm"
24,metformin,object,4,0,0.00,"No, Steady, Up, Down"
25,repaglinide,object,4,0,0.00,"No, Up, Steady, Down"
26,nateglinide,object,4,0,0.00,"No, Steady, Down, Up"
27,chlorpropamide,object,4,0,0.00,"No, Steady, Down, Up"
28,glimepiride,object,4,0,0.00,"No, Steady, Down, Up"
29,acetohexamide,object,2,0,0.00,"No, Steady"
30,glipizide,object,4,0,0.00,"No, Steady, Up, Down"
31,glyburide,object,4,0,0.00,"No, Steady, Up, Down"
32,tolbutamide,object,2,0,0.00,"No, Steady"
33,pioglitazone,object,4,0,0.00,"No, Steady, Up, Down"
34,rosiglitazone,object,4,0,0.00,"No, Steady, Up, Down"
35,acarbose,object,4,0,0.00,"No, Steady, Up, Down"
36,miglitol,object,4,0,0.00,"No, Steady, Down, Up"
37,troglitazone,object,2,0,0.00,"No, Steady"
38,tolazamide,object,3,0,0.00,"No, Steady, Up"
39,examide,object,1,0,0.00,No
40,citoglipton,object,1,0,0.00,No
41,insulin,object,4,0,0.00,"No, Up, Steady, Down"
42,glyburide-metformin,object,4,0,0.00,"No, Steady, Down, Up"
43,glipizide-metformin,object,2,0,0.00,"No, Steady"
44,glimepiride-pioglitazone,object,2,0,0.00,"No, Steady"
45,metformin-rosiglitazone,object,2,0,0.00,"No, Steady"
46,metformin-pioglitazone,object,2,0,0.00,"No, Steady"
47,change,object,2,0,0.00,"No, Ch"
48,diabetesMed,object,2,0,0.00,"No, Yes"
49,readmitted,object,3,0,0.00,"NO, >30, <30"

In [8]:
missing.to_csv(
    REPORT_DIR / "uci_missingness_summary.csv"
)

In [9]:
rows = []

for col in work.columns:
    rows.append({
        "variable": col,
        "pandas_dtype": str(work[col].dtype),
        "unique_values": work[col].nunique(dropna=True),
        "missing_n": work[col].isna().sum(),
        "missing_pct": round(work[col].isna().mean() * 100, 2),
        "example_values": ", ".join(
            map(str, work[col].dropna().unique()[:5])
        )
    })

dictionary = pd.DataFrame(rows)

dictionary

,variable,pandas_dtype,unique_values,missing_n,missing_pct,example_values
0,encounter_id,int64,101766,0,0.00,"2278392, 149190, 64410, 500364, 16680"
1,patient_nbr,int64,71518,0,0.00,"8222157, 55629189, 86047875, 82442376, 42519267"
2,race,object,5,2273,2.23,"Caucasian, AfricanAmerican, Other, Asian, Hisp..."
3,gender,object,3,0,0.00,"Female, Male, Unknown/Invalid"
4,age,object,10,0,0.00,"[0-10), [10-20), [20-30), [30-40), [40-50)"
5,weight,object,9,98569,96.86,"[75-100), [50-75), [0-25), [100-125), [25-50)"
6,admission_type_id,int64,8,0,0.00,"6, 1, 2, 3, 4"
7,discharge_disposition_id,int64,26,0,0.00,"25, 1, 3, 6, 2"
8,admission_source_id,int64,17,0,0.00,"1, 7, 2, 4, 5"
9,time_in_hospital,int64,14,0,0.00,"1, 3, 2, 4, 5"
10,payer_code,object,17,40256,39.56,"MC, MD, HM, UN, BC"
11,medical_specialty,object,72,49949,49.08,"Pediatrics-Endocrinology, InternalMedicine, Fa..."
12,num_lab_procedures,int64,118,0,0.00,"41, 59, 11, 44, 51"
13,num_procedures,int64,7,0,0.00,"0, 5, 1, 6, 2"
14,num_medications,int64,75,0,0.00,"1, 18, 13, 16, 8"
15,number_outpatient,int64,39,0,0.00,"0, 2, 1, 5, 7"
16,number_emergency,int64,33,0,0.00,"0, 1, 2, 4, 3"
17,number_inpatient,int64,21,0,0.00,"0, 1, 2, 3, 6"
18,diag_1,object,716,21,0.02,"250.83, 276, 648, 8, 197"
19,diag_2,object,748,358,0.35,"250.01, 250, 250.43, 157, 411"
20,diag_3,object,789,1423,1.40,"255, V27, 403, 250, V45"
21,number_diagnoses,int64,16,0,0.00,"1, 9, 6, 7, 5"
22,max_glu_serum,object,3,96420,94.75,">300, Norm, >200"
23,A1Cresult,object,3,84748,83.28,">7, >8, Norm"
24,metformin,object,4,0,0.00,"No, Steady, Up, Down"
25,repaglinide,object,4,0,0.00,"No, Up, Steady, Down"
26,nateglinide,object,4,0,0.00,"No, Steady, Down, Up"
27,chlorpropamide,object,4,0,0.00,"No, Steady, Down, Up"
28,glimepiride,object,4,0,0.00,"No, Steady, Down, Up"
29,acetohexamide,object,2,0,0.00,"No, Steady"
30,glipizide,object,4,0,0.00,"No, Steady, Up, Down"
31,glyburide,object,4,0,0.00,"No, Steady, Up, Down"
32,tolbutamide,object,2,0,0.00,"No, Steady"
33,pioglitazone,object,4,0,0.00,"No, Steady, Up, Down"
34,rosiglitazone,object,4,0,0.00,"No, Steady, Up, Down"
35,acarbose,object,4,0,0.00,"No, Steady, Up, Down"
36,miglitol,object,4,0,0.00,"No, Steady, Down, Up"
37,troglitazone,object,2,0,0.00,"No, Steady"
38,tolazamide,object,3,0,0.00,"No, Steady, Up"
39,examide,object,1,0,0.00,No
40,citoglipton,object,1,0,0.00,No
41,insulin,object,4,0,0.00,"No, Up, Steady, Down"
42,glyburide-metformin,object,4,0,0.00,"No, Steady, Down, Up"
43,glipizide-metformin,object,2,0,0.00,"No, Steady"
44,glimepiride-pioglitazone,object,2,0,0.00,"No, Steady"
45,metformin-rosiglitazone,object,2,0,0.00,"No, Steady"
46,metformin-pioglitazone,object,2,0,0.00,"No, Steady"
47,change,object,2,0,0.00,"No, Ch"
48,diabetesMed,object,2,0,0.00,"No, Yes"
49,readmitted,object,3,0,0.00,"NO, >30, <30"

In [10]:
dictionary.to_csv(
    REPORT_DIR / "uci_data_dictionary_draft.csv",
    index=False
)

In [11]:
work["readmission_30d"] = (
    work["readmitted"] == "<30"
).astype(int)

In [12]:
target_summary = (
    work["readmission_30d"]
    .value_counts()
    .rename_axis("readmission_30d")
    .reset_index(name="n")
)

target_summary["percentage"] = (
    target_summary["n"] / len(work) * 100
)

target_summary

   readmission_30d      n  percentage
0                0  90409   88.840084
1                1  11357   11.159916

In [13]:
target_summary.to_csv(
    REPORT_DIR / "readmission_30d_distribution.csv",
    index=False
)

In [14]:
patient_encounters = (
    work.groupby("patient_nbr")
    .size()
    .rename("encounter_count")
)

patient_encounters.describe()

count    71518.000000
mean         1.422942
std          1.090740
min          1.000000
25%          1.000000
50%          1.000000
75%          1.000000
max         40.000000
Name: encounter_count, dtype: float64

In [15]:
print(
    "Unique patients:",
    work["patient_nbr"].nunique()
)

print(
    "Patients with >1 encounter:",
    (patient_encounters > 1).sum()
)

print(
    "Percentage with >1 encounter:",
    round(
        (patient_encounters > 1).mean() * 100,
        2
    )
)

print(
    "Maximum encounters:",
    patient_encounters.max()
)

Unique patients: 71518
Patients with >1 encounter: 16773
Percentage with >1 encounter: 23.45
Maximum encounters: 40

In [16]:
repeat_patients = patient_encounters[
    patient_encounters > 1
].sort_values(ascending=False)

repeat_patients.head(20)

patient_nbr
88785891    40
43140906    28
88227540    23
1660293     23
23199021    23
84428613    22
23643405    22
92709351    21
23398488    20
29903877    20
37096866    20
90609804    20
88789707    20
89472402    20
88681950    19
97391007    19
88479036    19
24011577    18
3401055     18
84348792    18
Name: encounter_count, dtype: int64

In [17]:
example_patient = repeat_patients.index[0]

work[
    work["patient_nbr"] == example_patient
][[
    "encounter_id",
    "patient_nbr",
    "age",
    "time_in_hospital",
    "number_inpatient",
    "readmitted",
    "readmission_30d"
]]

,encounter_id,patient_nbr,age,time_in_hospital,number_inpatient,readmitted,readmission_30d
38307,119039172,88785891,[20-30),1,0,>30,0
40252,125094312,88785891,[20-30),1,2,<30,1
40661,126171582,88785891,[20-30),5,3,>30,0
44515,137245596,88785891,[20-30),2,5,<30,1
45147,139425576,88785891,[20-30),2,6,<30,1
45986,141994242,88785891,[20-30),4,7,<30,1
50167,150986298,88785891,[20-30),1,9,<30,1
50393,151413846,88785891,[20-30),4,9,<30,1
50773,152188656,88785891,[20-30),1,10,<30,1
51519,153558456,88785891,[20-30),1,11,<30,1
52057,154527444,88785891,[20-30),1,12,>30,0
53771,157363182,88785891,[20-30),2,13,<30,1
54497,158500410,88785891,[20-30),3,13,>30,0
60263,168920160,88785891,[20-30),8,12,>30,0
62759,174689286,88785891,[20-30),3,11,<30,1
63165,175632402,88785891,[20-30),4,13,>30,0
65667,183194856,88785891,[20-30),2,11,>30,0
67968,191345028,88785891,[20-30),5,12,>30,0
71029,205106328,88785891,[20-30),1,7,<30,1
72068,210079272,88785891,[20-30),2,7,>30,0
74405,221588430,88785891,[20-30),1,8,<30,1
74876,223647786,88785891,[20-30),2,9,<30,1
75267,225428574,88785891,[20-30),2,9,>30,0
76525,230986482,88785891,[20-30),7,10,<30,1
76907,232655340,88785891,[20-30),4,11,>30,0
78355,239153370,88785891,[20-30),7,9,<30,1
78882,241426656,88785891,[20-30),3,10,<30,1
79202,242844252,88785891,[20-30),1,11,<30,1
79467,243967338,88785891,[20-30),1,12,>30,0
82693,257757342,88785891,[20-30),2,11,>30,0
87063,277490424,88785891,[20-30),7,11,<30,1
87854,281267754,88785891,[20-30),7,11,<30,1
88392,284109186,88785891,[20-30),3,12,>30,0
89964,291808098,88785891,[20-30),6,13,>30,0
90913,302508452,88785891,[20-30),5,11,<30,1
91444,309563132,88785891,[20-30),3,12,<30,1
97433,388509176,88785891,[20-30),5,8,<30,1
97732,392073212,88785891,[20-30),3,10,>30,0
99950,419611106,88785891,[20-30),2,12,>30,0
101385,438529178,88785891,[20-30),3,9,<30,1

In [18]:
work["discharge_disposition_id"].value_counts().sort_index()

discharge_disposition_id
1     60234
2      2128
3     13954
4       815
5      1184
6     12902
7       623
8       108
9        21
10        6
11     1642
12        3
13      399
14      372
15       63
16       11
17       14
18     3691
19        8
20        2
22     1993
23      412
24       48
25      989
27        5
28      139
Name: count, dtype: int64

In [19]:
discharge_analysis = (
    work.groupby("discharge_disposition_id")
    .agg(
        encounters=("encounter_id", "count"),
        readmissions=("readmission_30d", "sum"),
        readmission_rate=("readmission_30d", "mean")
    )
)

discharge_analysis["readmission_rate"] *= 100

discharge_analysis.sort_values(
    "encounters",
    ascending=False
)

                          encounters  readmissions  readmission_rate
discharge_disposition_id
1                              60234          5602          9.300395
3                              13954          2046         14.662462
6                              12902          1638         12.695706
18                              3691           459         12.435654
2                               2128           342         16.071429
22                              1993           552         27.696939
11                              1642             0          0.000000
5                               1184           247         20.861486
25                               989            92          9.302326
4                                815           104         12.760736
7                                623            90         14.446228
23                               412            30          7.281553
13                               399            19          4.761905
14                               372            24          6.451613
28                               139            51         36.690647
8                                108            15         13.888889
15                                63            28         44.444444
24                                48             7         14.583333
9                                 21             9         42.857143
17                                14             0          0.000000
16                                11             0          0.000000
19                                 8             0          0.000000
10                                 6             0          0.000000
27                                 5             0          0.000000
12                                 3             2         66.666667
20                                 2             0          0.000000

In [20]:
missing[
    missing["missing_pct"] > 0
]

                   missing_n  missing_pct
weight                 98569    96.858479
max_glu_serum          96420    94.746772
A1Cresult              84748    83.277322
medical_specialty      49949    49.082208
payer_code             40256    39.557416
race                    2273     2.233555
diag_3                  1423     1.398306
diag_2                   358     0.351787
diag_1                    21     0.020636

In [21]:
from pathlib import Path
print(Path.cwd())

C:\Users\Administrator\Downloads\tanzania-readmission-intelligence-platform-research-engine\notebooks\python

In [22]:
!git status

On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   02_cohort_and_data_dictionary.ipynb

no changes added to commit (use "git add" and/or "git commit -a")

In [23]:
!git add .
!git commit -m "Discharge analysis"
!git push origin main

warning: in the working copy of 'notebooks/python/02_cohort_and_data_dictionary.ipynb', LF will be replaced by CRLF the next time Git touches it

[main 91a29ed] Discharge analysis
 1 file changed, 543 insertions(+), 3 deletions(-)

To https://github.com/gabrielthedatawizard/tanzania-readmission-intelligence-platform-research-engine.git
   fd72ce0..91a29ed  main -> main

In [24]:
missing_groups = pd.cut(
    missing["missing_pct"],
    bins=[-0.01, 5, 20, 50, 80, 100],
    labels=[
        "0–5%",
        "5–20%",
        "20–50%",
        "50–80%",
        "80–100%"
    ]
)

missing.assign(
    missing_group=missing_groups
).sort_values(
    "missing_pct",
    ascending=False
)

                          missing_n  missing_pct missing_group
weight                        98569    96.858479       80–100%
max_glu_serum                 96420    94.746772       80–100%
A1Cresult                     84748    83.277322       80–100%
medical_specialty             49949    49.082208        20–50%
payer_code                    40256    39.557416        20–50%
race                           2273     2.233555          0–5%
diag_3                         1423     1.398306          0–5%
diag_2                          358     0.351787          0–5%
diag_1                           21     0.020636          0–5%
admission_type_id                 0     0.000000          0–5%
time_in_hospital                  0     0.000000          0–5%
admission_source_id               0     0.000000          0–5%
discharge_disposition_id          0     0.000000          0–5%
glimepiride                       0     0.000000          0–5%
age                               0     0.000000          0–5%
gender                            0     0.000000          0–5%
num_procedures                    0     0.000000          0–5%
num_lab_procedures                0     0.000000          0–5%
number_inpatient                  0     0.000000          0–5%
num_medications                   0     0.000000          0–5%
number_outpatient                 0     0.000000          0–5%
number_emergency                  0     0.000000          0–5%
repaglinide                       0     0.000000          0–5%
number_diagnoses                  0     0.000000          0–5%
metformin                         0     0.000000          0–5%
patient_nbr                       0     0.000000          0–5%
nateglinide                       0     0.000000          0–5%
chlorpropamide                    0     0.000000          0–5%
acetohexamide                     0     0.000000          0–5%
metformin-pioglitazone            0     0.000000          0–5%
glyburide                         0     0.000000          0–5%
diabetesMed                       0     0.000000          0–5%
encounter_id                      0     0.000000          0–5%
troglitazone                      0     0.000000          0–5%
tolbutamide                       0     0.000000          0–5%
pioglitazone                      0     0.000000          0–5%
rosiglitazone                     0     0.000000          0–5%
acarbose                          0     0.000000          0–5%
miglitol                          0     0.000000          0–5%
citoglipton                       0     0.000000          0–5%
tolazamide                        0     0.000000          0–5%
examide                           0     0.000000          0–5%
glipizide                         0     0.000000          0–5%
insulin                           0     0.000000          0–5%
glyburide-metformin               0     0.000000          0–5%
glipizide-metformin               0     0.000000          0–5%
glimepiride-pioglitazone          0     0.000000          0–5%
metformin-rosiglitazone           0     0.000000          0–5%
change                            0     0.000000          0–5%
readmitted                        0     0.000000          0–5%

In [25]:
identifier_columns = [
    "encounter_id",
    "patient_nbr"
]

In [26]:
variable_roles = {
    "identifier": [
        "encounter_id",
        "patient_nbr"
    ],

    "demographic": [
        "race",
        "gender",
        "age",
        "weight"
    ],

    "admission": [
        "admission_type_id",
        "discharge_disposition_id",
        "admission_source_id",
        "time_in_hospital"
    ],

    "utilization": [
        "number_outpatient",
        "number_emergency",
        "number_inpatient"
    ],

    "clinical_activity": [
        "num_lab_procedures",
        "num_procedures",
        "num_medications",
        "number_diagnoses"
    ],

    "diagnosis": [
        "diag_1",
        "diag_2",
        "diag_3"
    ],

    "laboratory": [
        "max_glu_serum",
        "A1Cresult"
    ],

    "target": [
        "readmitted",
        "readmission_30d"
    ]
}

In [27]:

# Get all column names from the dataset
all_columns = set(df.columns)

# Collect all columns listed in variable_roles
classified_columns = {
    column
    for columns in variable_roles.values()
    for column in columns
}

# Identify columns that exist in the dataset but are not classified
unclassified_columns = sorted(all_columns - classified_columns)

# Identify names in the dictionary that do not exist in the dataset
unknown_columns = sorted(classified_columns - all_columns)

print("Total dataset columns:", len(all_columns))
print("Classified columns:", len(classified_columns))
print("Unclassified columns:", len(unclassified_columns))

print("\nUnclassified columns:")
print(unclassified_columns)

print("\nNames not found in the dataset:")
print(unknown_columns)

Total dataset columns: 50
Classified columns: 24
Unclassified columns: 27

Unclassified columns:
['acarbose', 'acetohexamide', 'change', 'chlorpropamide', 'citoglipton', 'diabetesMed', 'examide', 'glimepiride', 'glimepiride-pioglitazone', 'glipizide', 'glipizide-metformin', 'glyburide', 'glyburide-metformin', 'insulin', 'medical_specialty', 'metformin', 'metformin-pioglitazone', 'metformin-rosiglitazone', 'miglitol', 'nateglinide', 'payer_code', 'pioglitazone', 'repaglinide', 'rosiglitazone', 'tolazamide', 'tolbutamide', 'troglitazone']

Names not found in the dataset:
['readmission_30d']

In [29]:

variable_roles = {
    "identifier": [
        "encounter_id",
        "patient_nbr"
    ],

    "demographic": [
        "race",
        "gender",
        "age",
        "weight"
    ],

    "admission": [
        "admission_type_id",
        "discharge_disposition_id",
        "admission_source_id",
        "time_in_hospital"
    ],

    "utilization": [
        "number_outpatient",
        "number_emergency",
        "number_inpatient"
    ],

    "clinical_activity": [
        "num_lab_procedures",
        "num_procedures",
        "num_medications",
        "number_diagnoses"
    ],

    "diagnosis": [
        "diag_1",
        "diag_2",
        "diag_3"
    ],

    "laboratory": [
        "max_glu_serum",
        "A1Cresult"
    ],

    "medication_management": [
        "change",
        "diabetesMed"
    ],

    "medications": [
        "acarbose",
        "acetohexamide",
        "chlorpropamide",
        "citoglipton",
        "examide",
        "glimepiride",
        "glimepiride-pioglitazone",
        "glipizide",
        "glipizide-metformin",
        "glyburide",
        "glyburide-metformin",
        "insulin",
        "metformin",
        "metformin-pioglitazone",
        "metformin-rosiglitazone",
        "miglitol",
        "nateglinide",
        "pioglitazone",
        "repaglinide",
        "rosiglitazone",
        "tolazamide",
        "tolbutamide",
        "troglitazone"
    ],

    "administrative": [
        "payer_code",
        "medical_specialty"
    ],

    "target": [
        "readmitted"
    ]
}

In [30]:

all_columns = set(df.columns)

classified_columns = {
    column
    for columns in variable_roles.values()
    for column in columns
}

unclassified_columns = sorted(all_columns - classified_columns)
unknown_columns = sorted(classified_columns - all_columns)

print("Total dataset columns:", len(all_columns))
print("Classified columns:", len(classified_columns))
print("Unclassified columns:", len(unclassified_columns))
print("\nUnclassified columns:", unclassified_columns)
print("Names not found in dataset:", unknown_columns)

Total dataset columns: 50
Classified columns: 50
Unclassified columns: 0

Unclassified columns: []
Names not found in dataset: []

In [31]:

import numpy as np

work = df.copy()

# Convert the dataset's question-mark placeholders to missing values
work = work.replace("?", np.nan)

# Create a binary outcome while preserving the original readmitted column
work["readmission_30d"] = (
    work["readmitted"] == "<30"
).astype(int)

print(work["readmission_30d"].value_counts().sort_index())
print(work["readmission_30d"].value_counts(normalize=True).mul(100).round(2))

readmission_30d
0    90409
1    11357
Name: count, dtype: int64
readmission_30d
0    88.84
1    11.16
Name: proportion, dtype: float64

### Outcome Definition: 30-Day Readmission

The primary outcome for the initial TRIP research prototype is a binary indicator derived from the original `readmitted` variable in the UCI Diabetes 130-US Hospitals dataset.

- `1`: The encounter was followed by a recorded readmission within 30 days (`readmitted == "<30"`).
- `0`: The encounter was followed by a readmission after 30 days (`">30"`) or had no recorded readmission (`"NO"`).

In the initial dataset, 11,357 of 101,766 encounters (11.16%) were classified as positive, while 90,409 encounters (88.84%) were classified as negative.

The negative category combines late readmissions and no recorded readmission. The outcome therefore measures early readmission against this combined comparison group.

These figures are preliminary descriptive statistics. Cohort eligibility, repeated encounters, missing data, and prediction timing must be examined before model development.

In [33]:

# 1. Check the original outcome categories
print("Original readmission categories:")
print(work["readmitted"].value_counts(dropna=False))

# 2. Confirm the derived target distribution
print("\nDerived target distribution:")
print(
    work["readmission_30d"]
    .value_counts()
    .sort_index()
)

# 3. Examine the number of encounters and unique patients
print("\nDataset structure:")
print("Total encounters:", len(work))
print("Unique patients:", work["patient_nbr"].nunique())
print(
    "Patients with multiple encounters:",
    (work["patient_nbr"].value_counts() > 1).sum()
)

# 4. Check for missing patient identifiers
print(
    "Missing patient identifiers:",
    work["patient_nbr"].isna().sum()
)

Original readmission categories:
readmitted
NO     54864
>30    35545
<30    11357
Name: count, dtype: int64

Derived target distribution:
readmission_30d
0    90409
1    11357
Name: count, dtype: int64

Dataset structure:
Total encounters: 101766
Unique patients: 71518
Patients with multiple encounters: 16773
Missing patient identifiers: 0

In [34]:

total_encounters = len(work)
unique_patients = work["patient_nbr"].nunique()

print("Encounters per unique patient:",
      round(total_encounters / unique_patients, 2))

print("Encounters beyond one per patient:",
      total_encounters - unique_patients)

Encounters per unique patient: 1.42
Encounters beyond one per patient: 30248

In [35]:

print("Discharge disposition codes:")
print(
    work["discharge_disposition_id"]
    .value_counts(dropna=False)
    .sort_index()
)

print("\nMissing values in key variables:")
key_variables = [
    "patient_nbr",
    "readmitted",
    "discharge_disposition_id",
    "admission_type_id",
    "admission_source_id",
    "time_in_hospital"
]

print(work[key_variables].isna().sum())

Discharge disposition codes:
discharge_disposition_id
1     60234
2      2128
3     13954
4       815
5      1184
6     12902
7       623
8       108
9        21
10        6
11     1642
12        3
13      399
14      372
15       63
16       11
17       14
18     3691
19        8
20        2
22     1993
23      412
24       48
25      989
27        5
28      139
Name: count, dtype: int64

Missing values in key variables:
patient_nbr                 0
readmitted                  0
discharge_disposition_id    0
admission_type_id           0
admission_source_id         0
time_in_hospital            0
dtype: int64

In [36]:
print(mapping_text)

admission_type_id,description
1,Emergency
2,Urgent
3,Elective
4,Newborn
5,Not Available
6,NULL
7,Trauma Center
8,Not Mapped
,
discharge_disposition_id,description
1,Discharged to home
2,Discharged/transferred to another short term hospital
3,Discharged/transferred to SNF
4,Discharged/transferred to ICF
5,Discharged/transferred to another type of inpatient care institution
6,Discharged/transferred to home with home health service
7,Left AMA
8,Discharged/transferred to home under care of Home IV provider
9,Admitted as an inpatient to this hospital
10,Neonate discharged to another hospital for neonatal aftercare
11,Expired
12,Still patient or expected to return for outpatient services
13,Hospice / home
14,Hospice / medical facility
15,Discharged/transferred within this institution to Medicare approved swing bed
16,Discharged/transferred/referred another institution for outpatient services
17,Discharged/transferred/referred to this institution for outpatient services
18,NULL
19,"Expired at home. Medicaid only, hospice."
20,"Expired in a medical facility. Medicaid only, hospice."
21,"Expired, place unknown. Medicaid only, hospice."
22,Discharged/transferred to another rehab fac including rehab units of a hospital .
23,Discharged/transferred to a long term care hospital.
24,Discharged/transferred to a nursing facility certified under Medicaid but not certified under Medicare.
25,Not Mapped
26,Unknown/Invalid
30,Discharged/transferred to another Type of Health Care Institution not Defined Elsewhere
27,Discharged/transferred to a federal health care facility.
28,Discharged/transferred/referred to a psychiatric hospital of psychiatric distinct part unit of a hospital
29,Discharged/transferred to a Critical Access Hospital (CAH).
,
admission_source_id,description
1, Physician Referral
2,Clinic Referral
3,HMO Referral
4,Transfer from a hospital
5, Transfer from a Skilled Nursing Facility (SNF)
6, Transfer from another health care facility
7, Emergency Room
8, Court/Law Enforcement
9, Not Available
10, Transfer from critial access hospital
11,Normal Delivery
12, Premature Delivery
13, Sick Baby
14, Extramural Birth
15,Not Available
17,NULL
18, Transfer From Another Home Health Agency
19,Readmission to Same Home Health Agency
20, Not Mapped
21,Unknown/Invalid
22, Transfer from hospital inpt/same fac reslt in a sep claim
23, Born inside this hospital
24, Born outside this hospital
25, Transfer from Ambulatory Surgery Center
26,Transfer from Hospice

['encounter_id',
 'patient_nbr',
 'race',
 'gender',
 'age',
 'weight',
 'admission_type_id',
 'discharge_disposition_id',
 'admission_source_id',
 'time_in_hospital',
 'payer_code',
 'medical_specialty',
 'num_lab_procedures',
 'num_procedures',
 'num_medications',
 'number_outpatient',
 'number_emergency',
 'number_inpatient',
 'diag_1',
 'diag_2',
 'diag_3',
 'number_diagnoses',
 'max_glu_serum',
 'A1Cresult',
 'metformin',
 'repaglinide',
 'nateglinide',
 'chlorpropamide',
 'glimepiride',
 'acetohexamide',
 'glipizide',
 'glyburide',
 'tolbutamide',
 'pioglitazone',
 'rosiglitazone',
 'acarbose',
 'miglitol',
 'troglitazone',
 'tolazamide',
 'examide',
 'citoglipton',
 'insulin',
 'glyburide-metformin',
 'glipizide-metformin',
 'glimepiride-pioglitazone',
 'metformin-rosiglitazone',
 'metformin-pioglitazone',
 'change',
 'diabetesMed',
 'readmitted']

In [51]:

print(mapping_text)

admission_type_id,description
1,Emergency
2,Urgent
3,Elective
4,Newborn
5,Not Available
6,NULL
7,Trauma Center
8,Not Mapped
,
discharge_disposition_id,description
1,Discharged to home
2,Discharged/transferred to another short term hospital
3,Discharged/transferred to SNF
4,Discharged/transferred to ICF
5,Discharged/transferred to another type of inpatient care institution
6,Discharged/transferred to home with home health service
7,Left AMA
8,Discharged/transferred to home under care of Home IV provider
9,Admitted as an inpatient to this hospital
10,Neonate discharged to another hospital for neonatal aftercare
11,Expired
12,Still patient or expected to return for outpatient services
13,Hospice / home
14,Hospice / medical facility
15,Discharged/transferred within this institution to Medicare approved swing bed
16,Discharged/transferred/referred another institution for outpatient services
17,Discharged/transferred/referred to this institution for outpatient services
18,NULL
19,"Expired at home. Medicaid only, hospice."
20,"Expired in a medical facility. Medicaid only, hospice."
21,"Expired, place unknown. Medicaid only, hospice."
22,Discharged/transferred to another rehab fac including rehab units of a hospital .
23,Discharged/transferred to a long term care hospital.
24,Discharged/transferred to a nursing facility certified under Medicaid but not certified under Medicare.
25,Not Mapped
26,Unknown/Invalid
30,Discharged/transferred to another Type of Health Care Institution not Defined Elsewhere
27,Discharged/transferred to a federal health care facility.
28,Discharged/transferred/referred to a psychiatric hospital of psychiatric distinct part unit of a hospital
29,Discharged/transferred to a Critical Access Hospital (CAH).
,
admission_source_id,description
1, Physician Referral
2,Clinic Referral
3,HMO Referral
4,Transfer from a hospital
5, Transfer from a Skilled Nursing Facility (SNF)
6, Transfer from another health care facility
7, Emergency Room
8, Court/Law Enforcement
9, Not Available
10, Transfer from critial access hospital
11,Normal Delivery
12, Premature Delivery
13, Sick Baby
14, Extramural Birth
15,Not Available
17,NULL
18, Transfer From Another Home Health Agency
19,Readmission to Same Home Health Agency
20, Not Mapped
21,Unknown/Invalid
22, Transfer from hospital inpt/same fac reslt in a sep claim
23, Born inside this hospital
24, Born outside this hospital
25, Transfer from Ambulatory Surgery Center
26,Transfer from Hospice

In [52]:

position = mapping_text.find("discharge_disposition_id")

print("Section position:", position)
print(mapping_text[position:position + 5000])

Section position: 126
discharge_disposition_id,description
1,Discharged to home
2,Discharged/transferred to another short term hospital
3,Discharged/transferred to SNF
4,Discharged/transferred to ICF
5,Discharged/transferred to another type of inpatient care institution
6,Discharged/transferred to home with home health service
7,Left AMA
8,Discharged/transferred to home under care of Home IV provider
9,Admitted as an inpatient to this hospital
10,Neonate discharged to another hospital for neonatal aftercare
11,Expired
12,Still patient or expected to return for outpatient services
13,Hospice / home
14,Hospice / medical facility
15,Discharged/transferred within this institution to Medicare approved swing bed
16,Discharged/transferred/referred another institution for outpatient services
17,Discharged/transferred/referred to this institution for outpatient services
18,NULL
19,"Expired at home. Medicaid only, hospice."
20,"Expired in a medical facility. Medicaid only, hospice."
21,"Expired, place unknown. Medicaid only, hospice."
22,Discharged/transferred to another rehab fac including rehab units of a hospital .
23,Discharged/transferred to a long term care hospital.
24,Discharged/transferred to a nursing facility certified under Medicaid but not certified under Medicare.
25,Not Mapped
26,Unknown/Invalid
30,Discharged/transferred to another Type of Health Care Institution not Defined Elsewhere
27,Discharged/transferred to a federal health care facility.
28,Discharged/transferred/referred to a psychiatric hospital of psychiatric distinct part unit of a hospital
29,Discharged/transferred to a Critical Access Hospital (CAH).
,
admission_source_id,description
1, Physician Referral
2,Clinic Referral
3,HMO Referral
4,Transfer from a hospital
5, Transfer from a Skilled Nursing Facility (SNF)
6, Transfer from another health care facility
7, Emergency Room
8, Court/Law Enforcement
9, Not Available
10, Transfer from critial access hospital
11,Normal Delivery
12, Premature Delivery
13, Sick Baby
14, Extramural Birth
15,Not Available
17,NULL
18, Transfer From Another Home Health Agency
19,Readmission to Same Home Health Agency
20, Not Mapped
21,Unknown/Invalid
22, Transfer from hospital inpt/same fac reslt in a sep claim
23, Born inside this hospital
24, Born outside this hospital
25, Transfer from Ambulatory Surgery Center
26,Transfer from Hospice

In [54]:

!git status

On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   02_cohort_and_data_dictionary.ipynb

no changes added to commit (use "git add" and/or "git commit -a")

In [58]:
from pathlib import Path

current = Path.cwd()
repo_root = next(
    (p for p in current.parents if (p / ".git").exists()),
    None
)

print("Repository root:", repo_root)

Repository root: C:\Users\Administrator\Downloads\tanzania-readmission-intelligence-platform-research-engine

In [59]:
notebook = repo_root / "notebooks" / "python" / "02_cohort_and_data_dictionary.ipynb"

print("Notebook exists:", notebook.exists())
print("Notebook path:", notebook)

Notebook exists: True
Notebook path: C:\Users\Administrator\Downloads\tanzania-readmission-intelligence-platform-research-engine\notebooks\python\02_cohort_and_data_dictionary.ipynb

In [64]:
!git add 02_cohort_and_data_dictionary.ipynb

warning: in the working copy of 'notebooks/python/02_cohort_and_data_dictionary.ipynb', LF will be replaced by CRLF the next time Git touches it

In [65]:
!git commit -m "analysis: update discharge mappings and cohort planning"

[main 7253c20] analysis: update discharge mappings and cohort planning
 1 file changed, 808 insertions(+), 4 deletions(-)

In [66]:
!git push

To https://github.com/gabrielthedatawizard/tanzania-readmission-intelligence-platform-research-engine.git
   91a29ed..7253c20  main -> main